# Generated by Django 4.2.1 on 2023-07-18 16:59

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(unique=True, verbose_name='Nombre del area')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(unique=True, verbose_name='Nombre del rol administrativo')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Tutores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Primer Nombre')),
                ('nombre_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Nombre')),
                ('apellido_1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Primer Apellido')),
                ('apellido_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Apellido')),
                ('tipo_documentacion', models.CharField(choices=[('V', 'Venezolano')], default='V', max_length=1)),
                ('cedula', models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='Cedula')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.area')),
            ],
            options={
                'verbose_name': 'Tutor',
                'verbose_name_plural': 'Tutores',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(unique=True, verbose_name='Nombre del programa')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.area')),
            ],
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=250, unique=True)),
                ('nombre_1', models.CharField(max_length=50, verbose_name='Primer Nombre')),
                ('nombre_2', models.CharField(max_length=50, verbose_name='Segundo Nombre')),
                ('apellido_1', models.CharField(max_length=50, verbose_name='Primer Apellido')),
                ('apellido_2', models.CharField(max_length=50, verbose_name='Segundo Apellido')),
                ('tipo_documentacion', models.CharField(choices=[('V', 'Venezolano')], default='V', max_length=1)),
                ('cedula', models.CharField(max_length=8, unique=True, verbose_name='Cedula')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo Electronico')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.area')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.rol')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
