# Generated by Django 5.0.2 on 2024-02-20 12:02

import django.core.validators
import django.db.models.deletion
import gdstorage.storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_SC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('tematica', models.CharField(max_length=200)),
                ('periodo', models.CharField(choices=[('2000-1', '2000-1'), ('2000-2', '2000-2'), ('2001-1', '2001-1'), ('2001-2', '2001-2'), ('2002-1', '2002-1'), ('2002-2', '2002-2'), ('2003-1', '2003-1'), ('2003-2', '2003-2'), ('2004-1', '2004-1'), ('2004-2', '2004-2'), ('2005-1', '2005-1'), ('2005-2', '2005-2'), ('2006-1', '2006-1'), ('2006-2', '2006-2'), ('2007-1', '2007-1'), ('2007-2', '2007-2'), ('2008-1', '2008-1'), ('2008-2', '2008-2'), ('2009-1', '2009-1'), ('2009-2', '2009-2'), ('2010-1', '2010-1'), ('2010-2', '2010-2'), ('2011-1', '2011-1'), ('2011-2', '2011-2'), ('2012-1', '2012-1'), ('2012-2', '2012-2'), ('2013-1', '2013-1'), ('2013-2', '2013-2'), ('2014-1', '2014-1'), ('2014-2', '2014-2'), ('2015-1', '2015-1'), ('2015-2', '2015-2'), ('2016-1', '2016-1'), ('2016-2', '2016-2'), ('2017-1', '2017-1'), ('2017-2', '2017-2'), ('2018-1', '2018-1'), ('2018-2', '2018-2'), ('2019-1', '2019-1'), ('2019-2', '2019-2'), ('2020-1', '2020-1'), ('2020-2', '2020-2'), ('2021-1', '2021-1'), ('2021-2', '2021-2'), ('2022-1', '2022-1'), ('2022-2', '2022-2'), ('2023-1', '2023-1'), ('2023-2', '2023-2'), ('2024-1', '2024-1'), ('2024-2', '2024-2'), ('2025-1', '2025-1'), ('2025-2', '2025-2'), ('2026-1', '2026-1'), ('2026-2', '2026-2'), ('2027-1', '2027-1'), ('2027-2', '2027-2'), ('2028-1', '2028-1'), ('2028-2', '2028-2'), ('2029-1', '2029-1'), ('2029-2', '2029-2'), ('2030-1', '2030-1'), ('2030-2', '2030-2'), ('2031-1', '2031-1'), ('2031-2', '2031-2'), ('2032-1', '2032-1'), ('2032-2', '2032-2'), ('2033-1', '2033-1'), ('2033-2', '2033-2'), ('2034-1', '2034-1'), ('2034-2', '2034-2'), ('2035-1', '2035-1'), ('2035-2', '2035-2'), ('2036-1', '2036-1'), ('2036-2', '2036-2'), ('2037-1', '2037-1'), ('2037-2', '2037-2'), ('2038-1', '2038-1'), ('2038-2', '2038-2'), ('2039-1', '2039-1'), ('2039-2', '2039-2'), ('2040-1', '2040-1'), ('2040-2', '2040-2'), ('2041-1', '2041-1'), ('2041-2', '2041-2'), ('2042-1', '2042-1'), ('2042-2', '2042-2'), ('2043-1', '2043-1'), ('2043-2', '2043-2'), ('2044-1', '2044-1'), ('2044-2', '2044-2'), ('2045-1', '2045-1'), ('2045-2', '2045-2'), ('2046-1', '2046-1'), ('2046-2', '2046-2'), ('2047-1', '2047-1'), ('2047-2', '2047-2'), ('2048-1', '2048-1'), ('2048-2', '2048-2'), ('2049-1', '2049-1'), ('2049-2', '2049-2'), ('2050-1', '2050-1'), ('2050-2', '2050-2')], max_length=6, verbose_name='Periodos del area')),
                ('tipo_proyecto', models.CharField(choices=[('SC', 'Servicio Comunitario'), ('PreG', 'Pre-Grado'), ('PosG', 'Post-Grado')], default='SC', max_length=4)),
                ('resumen', models.TextField(blank=True, null=True)),
                ('ubicacion_servicio', models.CharField(max_length=200)),
                ('file', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='./proyectos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg'])])),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.area')),
                ('coordinador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.programa')),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.tutores')),
            ],
            options={
                'verbose_name': 'Proyecto de servicio comunitario',
                'verbose_name_plural': 'Proyectos de servicio comunitario',
            },
        ),
    ]
